---
title: "k clustering"
author: "Imran"
date: "07/09/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
```

```{r}
#import test data
d1 <- read.table("d1.txt", quote="\"", comment.char="")

d1 <- as.matrix(d1)
```

```{r}
# define number of cluster
cluster <- 3

c_initial <- c(0,1,2)
```



```{r}
#first centroid = first 2 data
centroid <- d1[1:cluster,]
cent_DF <- data.frame(c = c_initial, centroid)

d <- matrix(0, nrow = nrow(d1), ncol = cluster)

```

```{r}
#creating 0 vector for containing cluster number
c <- matrix(0, nrow = nrow(d1), ncol = 1)

#creating 0 matrix for temporary variable
updCentroid <- matrix(0, nrow = nrow(centroid), ncol = ncol(d1))

```

```{r}
#stopping criteria for converged centroids
status <- 10

#variable for counting iteration until the cluster converged
itr <- 0

```

```{r}
df <- data.frame(d1)

p1 <- ggplot(df,aes(V1, V2)) +
  geom_point(size=3)+ geom_point(data=cent_DF, color=c(2,3,4) , size=10)

ggsave(p1, file = "Data 2, 3 Cluster - initial.png", width = 40, height = 20, units = "cm")

while (status != 0)
{
  itr <- itr + 1
  
  fn <- paste("Data 2,", cluster, "Cluster - itr", itr, ".png", sep = " ")
}

```

```{r}
  #calculate distance each data to each centroid
  for (j in 1:cluster)
  {
    for (i in 1:nrow(d1))
    {
      d[i,j] = sqrt(sum((d1[i,1:ncol(d1)] - centroid[j,1:ncol(centroid)])^2))
    }
  }  
  

```

```{r}
  #assign cluster number on each data
  for(i in 1:nrow(d))
  {
    # if (d[i,1] < d[i,2]) c[i] = 0
    # else c[i] = 1
    
    c[i] <- (which(d[i,] == min(d[i,]), arr.ind = T)) - 1
  }
```



```{r}
#plot the clustering result
  df <- data.frame(c,d1)
  cent_DF <- data.frame(c = c_initial, centroid)
  
  # gg <- merge(df,aggregate(cbind(mean.V1=V1, mean.V2=V2)~c , df, mean), by="c")
  gg <- merge(df, cent_DF, by="c")

  plot <- ggplot(gg, aes(V1.x, V2.x, color=factor(c))) + geom_point(size=3) +
    geom_point(aes(x = V1.y, y = V2.y),size=5) +
    geom_segment(aes(x = V1.y, y = V2.y, xend = V1.x, yend = V2.x))

  ggsave(plot, file = fn, width = 40, height = 20, units = "cm")
```

```{r}
 #calculate the new centroid based on new clustered data
  compare <- cbind(d1, c)
  
  for (i in 1:cluster)
  {
    x <- subset(compare[,1:2], compare[,3] == i-1)
    
    for(j in 1:ncol(d1))
    {
      updCentroid[i,j] <- mean(x[,j])
    }
  }
```

```{r}
  #update the current centroid
  if(all(updCentroid == centroid)){
    status = 0
  }
  else {
    status = 1
    for (i in 1:cluster)
    {
      for (j in 1:ncol(centroid))
      {
        centroid[i,j] <- updCentroid[i,j]
      }
    } 
  }
}
```

